yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'Posts'

urlpatterns = [
    path('', views.index, name="index"),
    path('group/<slug:slug>/', views.group_posts, name="group_list"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/', views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'

handler403 = 'core.views.csrf_failure'

handler500 = 'core.views.internal_server_error'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from .constants import POST_START_WITH

User = get_user_model()


class Group(models.Model):
    """Модель для сортировки постов по группам."""

    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='URL',
    )
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Сообщество'
        verbose_name_plural = 'Сообщества'

    def __str__(self):
        return self.title


class Post(models.Model):
    """Модель для хранения постов."""

    text = models.TextField(
        verbose_name='Содержание',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Выберите автора',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return self.text[:POST_START_WITH]


class Comment(models.Model):
    """Модель для хранения комментариев к постам."""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        blank=True,
        null=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text='Добавьте комментарий',
    )
    text = models.TextField(
        max_length=500,
        verbose_name='Текст комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.title


class Follow(models.Model):
    """Модель для формирования подписки на авторов постов."""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор поста',
    )

    class Meta:
        verbose_name = 'Подписка на авторов'
        verbose_name_plural = 'Подписки на авторов'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_subscription'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    """Класс формы для создания нового поста."""

    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    """Класс формы для создания нового комментария."""
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from .models import User, Post, Group, Follow
from .forms import PostForm, CommentForm
from .utils import pagination


def index(request):
    """Функция-обработчик главной страницы проекта."""
    template = 'posts/index.html'
    post_list = Post.objects.select_related('group', 'author')
    page_obj = pagination(request, post_list)
    context = {'page_obj': page_obj}

    return render(request, template, context)


def group_posts(request, slug):
    """Функция-обработчик страницы сообществ."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('group', 'author')
    page_obj = pagination(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }

    return render(request, template, context)


def profile(request, username):
    """Функция-обработчик персональной страницы автора."""
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    user = request.user
    post_list = author.posts.select_related('group', 'author')
    page_obj = pagination(request, post_list)
    following = user.is_authenticated and Follow.objects.filter(
        user=user, author=author
    ).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }

    return render(request, template, context)


def post_detail(request, post_id):
    """Функция-обработчик страницы для просмотра отдельного поста."""
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }

    return render(request, template, context)


@login_required
def post_create(request):
    """Функция-обработчик создания нового поста."""
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()

        return redirect('posts:profile', username=post.author)

    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    """Функция-обработчик для редактирования поста."""
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:

        return redirect('posts:post_detail', post_id)

    form = PostForm(
        request.POST or None,
        instance=post,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()

        return redirect('posts:post_detail', post_id)

    return render(request, template, {
        'post': post,
        'form': form,
        'is_edit': True,
    })


@login_required
def add_comment(request, post_id):
    """Добавление комментария к посту"""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """
    Функция-обработчик, которая выводит посты авторов,
    на которых подписан текущий пользователь.
    """
    template = 'posts/follow.html'
    posts_to_sign = Post.objects.filter(
        author__following__user=request.user
    ).select_related('author', 'group')
    page_obj = pagination(request, posts_to_sign)
    context = {'page_obj': page_obj}

    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Функция-обработчик, позволяющая подписаться на автора."""
    author = get_object_or_404(User, username=username)
    if request.user != author and request.user.is_authenticated:
        Follow.objects.get_or_create(
            user=request.user,
            author=author,
        )

    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    """Функция-обработчик, позволяющая отписаться от автора."""
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()

    return redirect('posts:index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  <title> Редактировать запись</title>
{% else %}
  <title>Новый пост</title>
{% endif %}
{% endblock %} 
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
          <b>Редактировать пост</b> 
          {% else %}
          <b>Новый пост</b> 
          {% endif %}
        </div>
        <div class="card-body"> 
          {% load user_filters %}  
          {% include "includes/form_errors.html" %}
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            {% include "includes/form_cycle.html" %}
          {% endfor %}
           <div class="d-flex justify-content-end">
             <button type="submit" class="btn btn-primary">
               {% if is_edit %}
                 Сохранить
               {% else %}
                 Добавить
               {% endif %}    
             </button>
           </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock%} 
    

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}  
  <title>Мои подписки</title>
{% endblock %}
{% block content %}
  <div class="container py-2">
    {% include 'posts/includes/switcher.html' %}
    <h1>Мои любимые авторы и их посты</h1>
    {% for post in page_obj %}   
      {% include 'posts/includes/article.html' %}
    {% if not forloop.last %}<hr>{% endif %}     
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  <title>Группа {{ group.title }}</title>
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}   
      {% include 'posts/includes/article.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div> 
{% endblock %}
   

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block title %}  
  <title>Последние обновления на сайте</title>
{% endblock %}
{% block content %}
  <div class="container py-2">
    {% include 'posts/includes/switcher.html' %}
     <h1>Последние обновления на сайте</h1>
    {% cache 20 index_page  %}
    {% for post in page_obj %}   
      {% include 'posts/includes/article.html' %}
      {% if not forloop.last %}<hr>{% endif %}     
    {% endfor %}
    {% endcache %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
<title> Пост {{ post.text|truncatechars:30 }}</title>
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item list-group-item-warning">Дата публикации: {{ post.pub_date|date:"d E Y" }} </li>
        {% if post.group %} 
          <li class="list-group-item list-group-item-primary">Группа: {{ post.group.title }}
            <a href="{% url 'Posts:group_list' post.group.slug %}">все записи группы</a> 
         </li>
        {% endif %}
         <li class="list-group-item list-group-item-success">Автор: {{ post.author.get_full_name }} {{ post.author.username }}</li>
         <li class="list-group-item list-group-item-danger d-flex justify-content-between align-items-center">
            Всего постов автора:  <span>{{ post.author.posts.count }}</span>
         </li>
         <li class="list-group-item list-group-item-info">
           <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
         </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
    {% thumbnail post.image "350x400" crop='center' upscale=True as im %}
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" >
    {% endthumbnail %}
    <article class="col-12 col-md-9">
      <p>{{ post.text|linebreaksbr }}</p>
        {% if post.author == request.user %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать запись
          </a>
        {% endif %}
        {% include 'posts/includes/comments.html' %}
    </article>
  </div> 
</div>  
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
<title>Пройфайл пользователя {{ author.username }}</title>
{% endblock %}
{% block content %}
<div class="container py-2">
  <div class="mb-5">
    {% if user.is_authenticated %}
      {% if author != request.user %}
        {% if following %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
        {% else %} 
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
         Подписаться
        </a>
        {% endif %}
      {% endif %}
    {% endif %}
  </div>
  <h3>Все посты пользователя <span class="badge bg-info">{{ author.username }}</span></h3>
  <h4>Количество постов: <span class="badge bg-info">{{ author.posts.count }}</span></h4>
  <h4>Количество подписок: <span class="badge bg-info">{{ author.follower.count }}</span></h4>
  <h4>Количество подписчиков: <span class="badge bg-info">{{ author.following.count}}</span></h4>
    {% for post in page_obj %}          
    {% include 'posts/includes/article.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}  
</div>
{% endblock %}
  